# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"

minimal_mistakes_skin: default

url: "https://vhidvz.github.io"
baseurl: "/"

locale: "en-US"
encoding: "UTF-8"

# breadcrumbs: true
# breadcrumb_home_label : "Home"
# breadcrumb_separator  : "/"

date_format: "%Y-%m-%d"
logo: "/assets/images/logo.png"

title: "Vahid V."
email: vhid.vz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I always enjoy developing and I have been engaging in this field
  professionally since 2013. I am an expert in Python and TypeScript.
  enthusiastically explore new technologies for efficiency,
  always looking for new ways to solve the problem as efficiently as possible.
twitter_username: VhidVZ
github_username: vhidvz

search: true
search_full_content: true

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Tehran # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

author:
  name      : "Vahid V."
  avatar    : "/assets/images/profile.jpg"
  bio       : "Full Stack Developer"
  location  : "Iran, Tehran"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:vhid.vz@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VhidVZ/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vhidvz/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vahid-vakili-484674235/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VhidVZ/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vhidvz/"

repository: "vhidvz/vhidvz.github.io"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOHOQjMw"
    category_id          : "DIC_kwDOHOQjM84COvOO"
    mapping              : "pathname"
    reactions_enabled    : "1"
    input-position       : "top"
    theme                : "light"
    lang                 : "en"
    loading              : "lazy"

social:
  type:  Person
  name:  Vahid V.
  links:
    - "https://twitter.com/VhidVZ/"
    - "https://github.com/vhidvz/"

analytics:
  provider: "google"
  google:
    tracking_id: "G-9V579SRGP5"

# Reading Files
include:
  - _pages

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:title/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
      toc: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: false
      toc: true
      toc_sticky: true

# category_archive:
#   type: liquid
#   path: /categories/
tag_archive:
  type: liquid
  path: /blog/
